### PR TITLE
support errand boy for subprocess communication

### PR DESCRIPTION
**Pull request by snopoke**
This should help with out of memory errors.
@NoahCarnahan 

cc @benrudolph 

See https://github.com/greyside/errand-boy

### CODE REVIEW

**Comment by emord** [comment]
Should errand-boy be added to requirements.txt?

**Comment by snopoke** [comment]
This repo doesn't have a requirements.txt

**Comment by snopoke** [comment]
Also, its optional

**Comment by benrudolph** [comment]
sweet excited for this. should we at least put this in the HQ requirements? else how will errandboy get downloaded on deploy?

**Comment by snopoke** [comment]
@benrudolph I'm still working on that part

**Pull request merged**
