### PR TITLE
add new jar

### PR DESCRIPTION
**Pull request by wpride**
2.26 form translate jar

### CODE REVIEW

**Comment by czue** [comment]
2.26? does this need any QA or anything or g2g?

**Comment by wpride** [comment]
yeah passed to Clark since i think QA took a sanity pass last time

http://manage.dimagi.com/default.asp?218058#1095090

**Comment by czue** [comment]
:+1:

**Comment by wpride** [comment]
merging after QA signoff http://manage.dimagi.com/default.asp?218058

**Pull request merged**
