### PR TITLE
Use 2.24 form_translate jar

### PR DESCRIPTION
**Pull request by wpride**
Needed specifically for http://manage.dimagi.com/default.asp?89140#1041232

Not sure if we need to QA this or not?

@dannyroberts @czue

### CODE REVIEW

**Comment by czue** [comment]
@dannyroberts @snopoke  do you recall if we usually QA these? or do we have any automated tests for validation?

**Comment by snopoke** [comment]
I don't think we have any direct tests so probably good to do a basic QA

**Comment by czue** [comment]
@wpride can you get this on staging and ask the QA team to sanity test apps?

**Comment by wpride** [comment]
@czue ticket here http://manage.dimagi.com/default.asp?186139#1044172

**Comment by esoergel** [comment]
This is now on staging.

**Comment by wpride** [comment]
merging per sign off from Christy

**Comment by esoergel** [comment]
:+1:

**Comment by czue** [comment]
:tada:

**Pull request merged**
